use vim_core_rs::VimCoreSession;

unsafe extern "C" {
    fn vim_bridge_get_search_pattern() -> *const std::ffi::c_char;
    fn vim_bridge_is_hlsearch_active() -> std::ffi::c_int;
    fn vim_bridge_get_search_direction() -> std::ffi::c_int;

    // Using the types generated by bindgen would be ideal, but we will define them locally for this test.
    fn vim_bridge_get_search_highlights(window_id: std::ffi::c_int, start_row: std::ffi::c_int, end_row: std::ffi::c_int) -> MatchList;
    fn vim_bridge_free_match_list(list: MatchList);
    fn vim_bridge_get_cursor_match_info(window_id: std::ffi::c_int, row: std::ffi::c_int, col: std::ffi::c_int, max_count: std::ffi::c_int, timeout_ms: std::ffi::c_int) -> CursorMatchInfo;
}

#[repr(C)]
struct MatchRange {
    start_row: std::ffi::c_int,
    start_col: std::ffi::c_int,
    end_row: std::ffi::c_int,
    end_col: std::ffi::c_int,
    match_type: std::ffi::c_int,
}

#[repr(C)]
struct MatchList {
    ranges: *mut MatchRange,
    count: std::ffi::c_int,
}

#[repr(C)]
struct CursorMatchInfo {
    is_on_match: std::ffi::c_int,
    current_match_index: std::ffi::c_int,
    total_matches: std::ffi::c_int,
    status: std::ffi::c_int,
}

#[test]
fn test_c_ffi_search_pattern() {
    let mut session = VimCoreSession::new("test buffer\nmatch this\nmatch that\n").unwrap();

    // Set a search pattern in vim via ex command
    let _ = session.apply_ex_command("let @/ = 'match'");
    let _ = session.apply_ex_command("set hlsearch");

    unsafe {
        let pattern_ptr = vim_bridge_get_search_pattern();
        assert!(!pattern_ptr.is_null());

        let c_str = std::ffi::CStr::from_ptr(pattern_ptr);
        let pattern = c_str.to_str().unwrap();
        assert_eq!(pattern, "match");

        let is_hlsearch = vim_bridge_is_hlsearch_active();
        assert_eq!(is_hlsearch, 1);

        let dir = vim_bridge_get_search_direction();
        assert_eq!(dir, 1); // Forward search default

        // Test highlight extraction
        let hl_list = vim_bridge_get_search_highlights(1000, 1, 3);
        assert_eq!(hl_list.count, 2, "Should find 2 matches");
        if hl_list.count > 0 {
            let range = &*hl_list.ranges.offset(0);
            assert_eq!(range.start_row, 2);
            assert_eq!(range.start_col, 0); // "match" is at start of line 2
            assert_eq!(range.end_col, 5);
        }
        vim_bridge_free_match_list(hl_list);

        // Test cursor match info
        let info = vim_bridge_get_cursor_match_info(1000, 2, 0, 100, 100);
        assert_eq!(info.is_on_match, 1, "Cursor should be on match");
        assert_eq!(info.current_match_index, 1, "Should be the first match");
        assert_eq!(info.total_matches, 2, "Total 2 matches");
    }
}
